### ISSUE TITLE
feature request: Additional sites in dash

### ISSUE THREAD

**Issue by MBoegers** [RobinJ1995/be.robinj.ubuntu#10]
To increase Unity look-and-feel the dashboard should have some more pages like documents and messages. 
Messages could be a very big but very cool thing. maybe via widget?

**Comment by RobinJ1995** [comment]
Well the app has had support for "Lenses" (fetching search results from different places, including your local files) in the repository for some time. It just hasn't been released yet since I'm set on getting widget support working. So I think I can close this one.
Multiple pages in the Dash probably won't happen any time soon considering that the project is moving away from being an Ubuntu-only launcher (copyright issues), and something like that may not necessarily fit in with themes for different distro's.
